services:
  - type: web
    name: nsfw-mozaiku-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    region: singapore

envVars:
  - key: PYTHON_VERSION
    value: 3.10
